# Generated by Django 2.2.15 on 2020-11-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_intructions',
            new_name='cooking_instructions',
        ),
    ]
