# Generated by Django 2.2.15 on 2020-11-27 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20201125_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
        ),
    ]
