# Generated by Django 2.2.15 on 2020-11-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_ingredient_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
