# Generated by Django 2.2.15 on 2020-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_list',
        ),
    ]
